// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz2n1nSGr3Eclkw2cO9rJp2ebdSIUKOoM',
    appId: '1:64636347575:web:cb0c094441855ab4855932',
    messagingSenderId: '64636347575',
    projectId: 'robox-500fa',
    authDomain: 'robox-500fa.firebaseapp.com',
    storageBucket: 'robox-500fa.firebasestorage.app',
    measurementId: 'G-QVSKWEXMQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8zLlfyiyhc_SixygasBkKlrju2bPHw8Q',
    appId: '1:64636347575:android:479f312877ce04a3855932',
    messagingSenderId: '64636347575',
    projectId: 'robox-500fa',
    storageBucket: 'robox-500fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv7QAGy-jg5M51vLeJ_godHnqc2YBgDvE',
    appId: '1:64636347575:ios:d88f4ccb32d981a5855932',
    messagingSenderId: '64636347575',
    projectId: 'robox-500fa',
    storageBucket: 'robox-500fa.firebasestorage.app',
    iosBundleId: 'com.example.robox',
  );
}
